apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3JkMTIz  # rootpassword123
  mysql-password: dG9kb3Bhc3N3b3JkMTIz        # todopassword123